# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

  
    - name: Build Plugins
      run: mvn clean -B package --file pom.xml
    - run: mkdir staging && cp target/*-jar-with-dependencies.jar staging
    - run: cp *.sql staging
    - uses: actions/upload-artifact@v4
      with:
            name: Plugin
            path: staging
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
